# Generated by Django 4.2.2 on 2023-06-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_baza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baza',
            name='deadline',
        ),
        migrations.AddField(
            model_name='baza',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
