# Generated by Django 4.2.2 on 2023-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='link',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='team',
            name='link2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='link3',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='link4',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
