# Generated by Django 4.2.2 on 2023-06-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_rename_link_team_link1_team_link2_team_link3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='picture1',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
